spring.application.name=email-writer-ai

# Gemini API configuration  
spring.ai.google.genai.api-key=
spring.ai.google.genai.chat.options.model=gemini-2.0-flash

# Ollama API configuration
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2:latest

